version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"
  api:
    build: ./server
    ports:
      - "3000:3000"
    expose:
      - "3000"
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
volumes:
  mongodb_data_container: